# https://aka.ms/yaml

pr:
  branches:
    include:
    - feature/*
    - bugfix/*

pool:
  vmImage: 'Ubuntu-16.04'

resources:
  containers:
  - container: linux
    image: ubuntu-16.04

steps:
- bash: yarn install
  displayName: 'Install Yarn'

- bash: yarn run build-client
  displayName: 'Build client'

- bash: yarn run build-server
  displayName: 'Build server'

- bash: |
        docker-compose -f docker-compose.dev.yml up -d
        yarn run test-server
        docker-compose -f docker-compose.dev.yml down

  displayName: 'Test server'

  