version: '3'

services:
  db:
    image: "ravendb/ravendb"
    ports:
     - "8080:8080"
    environment:
     RAVEN_ARGS: "--Setup.Mode=None"
     RAVEN_Security_UnsecuredAccessAllowed: "PrivateNetwork."